###
GET http://localhost:5000/categories

###
POST http://localhost:5000/categories 

###
DELETE http://localhost:5000/categories/3

###
PUT http://localhost:5000/categories/3
Content-Type: application/json

{
  "name": "Updated Category Name"
}