GET http://localhost:5000/api/users/

###
GET http://localhost:5000/api/users/13

###

POST http://localhost:5000/api/users
Content-Type: application/json

{
  "name": "slametkopling",
  "email": "slametkopling@example.com",
  "nickname": "slametkopling",
  "password": "securepassword"
}

###
PUT http://localhost:5000/api/users/10
Content-Type: application/json

{
  "name": "Muhammad slamet",
  "nickname": "slimit"
}

###
DELETE http://localhost:5000/api/users/13