GET https://www.google.com

###
POST http://localhost:5000/users/
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe@example.com",
  "nickname": "johnd",
  "password": "securepassword"
}